apiVersion: kudo.dev/v1alpha1
kind: TestSuite
manifestDirs:
  - ./test/manifests/
commands:
  - command: kubectl apply -f https://mesosphere.github.io/kubeaddons/bundle.yaml
testDirs:
  - ./addons/zookeeper/0.x/
startKIND: true
timeout: 300
