---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: generic-application-operator
  labels:
    kubeaddons.mesosphere.io/name: generic-application-operator
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.1.3"
    appversion.kubeaddons.mesosphere.io/generic-application-operator: "0.1.3"
    stage.kubeaddons.mesosphere.io/generic-application-operator: Alpha
    catalog.kubeaddons.mesosphere.io/kudo-params: "https://raw.githubusercontent.com/kudobuilder/generic-application-operator/master/operator/params.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.16.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  kudoReference:
    package: generic-application
    repo: https://kudo-applications.storage.googleapis.com/
    version: "0.1.3"
    appVersion: 0.1.3
