---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: kafka
  labels:
    kubeaddons.mesosphere.io/name: kafka
    kubeaddons.mesosphere.io/hack-requires-defaultstorageclass: "true"
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "2.4.0-3"
    appversion.kubeaddons.mesosphere.io/kafka: "2.4.0"
    catalog.kubeaddons.mesosphere.io/kudo-params: "https://raw.githubusercontent.com/kudobuilder/operators/master/repository/kafka/operator/params.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.16.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  kudoReferences:
    - package: kafka
      name: kafka
      repo: https://kudo-repository.storage.googleapis.com/0.10.0
      version: 1.2.0
      parameters: |
        ZOOKEEPER_URI: zookeeper-zookeeper-0.zookeeper-hs:2181,zookeeper-zookeeper-1.zookeeper-hs:2181,zookeeper-zookeeper-2.zookeeper-hs:2181
    - package: zookeeper
      name: zookeeper
      repo: https://kudo-repository.storage.googleapis.com/0.10.0
      version: 0.3.0
